### ISSUE TITLE
ImportError: cannot import name 'hash_unicode' from 'murmurhash'

### ISSUE THREAD

**Issue by Code4SAFrankie** [explosion/spacy-stanza#66]
`import spacy_stanza` gives me this error:
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\spacy_stanza\__init__.py", line 2, in <module>
    from spacy import blank, Language
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\spacy\__init__.py", line 10, in <module>
    from thinc.api import prefer_gpu, require_gpu, require_cpu  # noqa: F401
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\thinc\api.py", line 22, in <module>
    from .layers import Dropout, Embed, expand_window, HashEmbed, LayerNorm, Linear
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\thinc\layers\__init__.py", line 53, in <module>
    from .strings2arrays import strings2arrays
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\thinc\layers\strings2arrays.py", line 2, in <module>
    from murmurhash import hash_unicode
ImportError: cannot import name 'hash_unicode' from 'murmurhash' (E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\murmurhash\__init__.py)
```

I am using `Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32`, which is WinPython on Windows 10 64 bit.

**Comment by Code4SAFrankie** [comment]
Works in WinPython 3.8.1 though

**Comment by adrianeboyd** [comment]
It sounds like a problem with your venv or spacy install. Sometimes `pip` doesn't upgrade packages cleanly. It's a frustrating suggestion, but can you try again with a brand new virtual environment?

**Comment by silviaegt** [comment]
did you get a solution for this @Code4SAFrankie other than running your code with Python 3.8.1? (It also worked for me - but I'm just curious of what the reason might be)

**Comment by Code4SAFrankie** [comment]
No, but my Python 3.7 is pretty messed up, since I don't use virtual environments.

**Comment by ozumpe** [comment]
I just had the same issue and solved it with.

pip uninstall murmurhash
pip uninstall spacy
pip install -U spacy
